// Created using the image.py script written by Patrick Hughes. He's a pretty cool guy.
//
// DO NOT EDIT THIS FILE. 
//
// This file is automatically generated. Any changes will be overwritten the next time images.py is invoked.

#define imgIcon114 (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"icon114"]; ZAssert(image, @"Image icon114 not found"); return image; }()

#define imgIconajustes (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"iconAjustes"]; ZAssert(image, @"Image iconAjustes not found"); return image; }()

#define imgHomebuttonwochevron (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"homeButtonWOChevron"]; ZAssert(image, @"Image homeButtonWOChevron not found"); return image; }()

#define imgCheckOkGrey (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"check_ok_grey"]; ZAssert(image, @"Image check_ok_grey not found"); return image; }()

#define imgHomeviewbg568h (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"HomeViewbg-568h"]; ZAssert(image, @"Image HomeViewbg-568h not found"); return image; }()

#define imgIconhistorial (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"iconHistorial"]; ZAssert(image, @"Image iconHistorial not found"); return image; }()

#define imgIconaprender (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"iconAprender"]; ZAssert(image, @"Image iconAprender not found"); return image; }()

#define imgCheckOkDarkGrey (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"check_ok_dark_grey"]; ZAssert(image, @"Image check_ok_dark_grey not found"); return image; }()

#define imgCheckNokRed (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"check_nok_red"]; ZAssert(image, @"Image check_nok_red not found"); return image; }()

#define imgSectorimage0 (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"sectorImage0"]; ZAssert(image, @"Image sectorImage0 not found"); return image; }()

#define imgIcon57 (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"icon57"]; ZAssert(image, @"Image icon57 not found"); return image; }()

#define imgCheckNokDarkGrey (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"check_nok_dark_grey"]; ZAssert(image, @"Image check_nok_dark_grey not found"); return image; }()

#define imgInfo (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"info"]; ZAssert(image, @"Image info not found"); return image; }()

#define imgHomebutton (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"homeButton"]; ZAssert(image, @"Image homeButton not found"); return image; }()

#define imgIconevaluar (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"iconEvaluar"]; ZAssert(image, @"Image iconEvaluar not found"); return image; }()

#define imgCheckmark64 (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"checkmark_64"]; ZAssert(image, @"Image checkmark_64 not found"); return image; }()

#define imgWhiteCircularBg1 (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"white-circular-bg1"]; ZAssert(image, @"Image white-circular-bg1 not found"); return image; }()

#define imgCheckNokGrey (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"check_nok_grey"]; ZAssert(image, @"Image check_nok_grey not found"); return image; }()

#define imgStar (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"star"]; ZAssert(image, @"Image star not found"); return image; }()

#define imgHomeviewbg (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"HomeViewbg"]; ZAssert(image, @"Image HomeViewbg not found"); return image; }()

#define imgCheckOkGreen (UIImage*)^{ UIImage *image = [UIImage imageNamed:@"check_ok_green"]; ZAssert(image, @"Image check_ok_green not found"); return image; }()

